source 'https://github.com/CocoaPods/Specs'

xcodeproj 'Tests'
workspace '../Tapglue SDK'
inhibit_all_warnings!

target :ios do
  platform :ios, '7.0'
  link_with 'Tests'
  pod 'Expecta', '~> 1.0.0'
end
