source 'https://github.com/CocoaPods/Specs'

project 'Tests'
workspace '../Tapglue SDK'
inhibit_all_warnings!

target :Tests do
  platform :ios, '7.0'
  inherit! :search_paths
  pod 'Expecta', '~> 1.0.0'
end

target :IntegrationTests do
  platform :ios, '7.0'
  inherit! :search_paths
  pod 'Expecta', '~> 1.0.0'
end
